server:
  runMode: debug      # runMode: debug or release
  addr: :8074         # server addr
  readTimeout: 60     # read timeout
  writeTimeout: 60    # write timeout
  swagger: true       # swagger switch: true or false
