info:
  contact: {}
paths:
  /api/v1/get_test:
    get:
      description: test, return hello
      parameters:
      - description: apikey
        in: query
        name: apikey
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: test
  /api/v1/health:
    get:
      description: API接口健康检查，Get请求
      produces:
      - application/json
      responses:
        "10000":
          description: ok
          schema:
            type: string
      summary: 健康检查
  /api/v1/post_test:
    post:
      description: test, return hello
      parameters:
      - description: apikey
        in: body
        name: apikey
        required: true
        schema:
          type: string
      - description: param
        in: body
        name: param
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: test
swagger: "2.0"
